### ISSUE TITLE
Add support for reaction_xxx events

### ISSUE THREAD

**Issue by l12s** [l12s/node-slack-client#11]

**Comment by mbland** [comment]
Thanks for this! But I have a question about the `reaction_added` API event itself.

Should the `item.message` payload contain the full message data? Or do I need to use what's there to fetch the message data separately?
 
According to [reactions.list](https://api.slack.com/methods/reactions.list), it seems that the `item` member of [reaction_added](https://api.slack.com/events/reaction_added) might actually contain the `message` data, including the list of `reactions`. However my latest debug hack is showing that it only contains:

```json
{
  "type": "reaction_added",
  "user": "XXX",
  "item": {
    "type": "message",
    "channel": "YYY",
    "ts": "0000000000.000000"
  },
  "reaction": "evergreen_tree",
  "event_ts": "0000000000.000000"
}
```

That matches [what @msabramo posted in slackhq/node-slack-client#59](https://github.com/slackhq/node-slack-client/pull/59#issuecomment-152586805). (At least my script and the hacks to patch in the `reaction_added` message are working. :smiley:)

cc: @afeld @ccostino @jeremiak @andrewmaier @melodykramer @mtorres253

**Comment by l12s** [comment]
It's a sparse representation right now. So, either I'd:
- look at a local cache for the details of the message
- fetch the message from history via https://api.slack.com/methods/channels.history
- store the sparse message and rely on lazy fetchHistory calls

We're also looking at improving some of the docs there to clarify what the API provides, @episod may be able to add some more info on that.

**Comment by l12s** [comment]
You can see my branch where I'm working on reaction_xxx support here: https://github.com/l12s/node-slack-client/tree/emoji_reactions

**Comment by l12s** [comment]
Ok, basic support implemented for reactions to messages.
