### ISSUE TITLE
RTM client will not successfully connect as of 0bc36e0e7d9128e5c7a2c7f46d9964c934859433

### ISSUE THREAD

**Issue by HandyAndyShortStack** [l12s/node-slack-client#26]
Thanks for your work on this library!  It is definitely an improvement over 1.x.

I am stuck using master at 56763674a3426b0f01a8fb519d282f426c33df63 because some changes introduced with 0bc36e0e7d9128e5c7a2c7f46d9964c934859433 makes the RTM client unable to connect with slack.

My key is for a bot user, if that makes any difference.

**Comment by xomyaq** [comment]
Example doesn't work too.

**Comment by ekmartin** [comment]
The example needs an update, `RtmClient` now takes in the token as its first argument (instead of a `WebClient` instance), see https://github.com/l12s/node-slack-client/blob/master/lib%2Fclients%2Frtm%2Fclient.js#L43.
