### ISSUE TITLE
dm.open returns "user not found" for valid user

### ISSUE THREAD

**Issue by andrewpbrett** [l12s/node-slack-client#28]
Hi - I might be doing something wrong here, but when I test the endpoint [here](https://api.slack.com/methods/im.open/test) it works as expected. I can also use this `webClient` object to to `users.list` and get back a list of users, including the one with the ID I'm passing below. However when I make the `dm.open` call below, I get a response of `{"error": "user_not_found", "ok": false }`

Any ideas? 

    var slackClient = require('slack-client');
    var WebClient = slackClient.WebClient;
    var webClient = new WebClient(rtm._webClient._token); // not sure if this is the right way to do that...
    webClient.dm.open({ "user": "U0EFW46JC" }, function(error, response) {
     if (!response.ok) { return; }
     rtm.send({
       id: 1,
       type: "message",
       channel: response.channel.id,
       text: req.body.message
     });
    });

**Comment by ekmartin** [comment]
The first argument should be just the user id as a string, not an object. I.e. `webClient.dm.open('U0EFW46JC', function(error, response) {`

Source here: https://github.com/l12s/node-slack-client/blob/master/lib%2Fclients%2Fweb%2Ffacets%2Fdm.js#L89-L95

**Comment by andrewpbrett** [comment]
@ekmartin Thanks for taking a look Martin! Working great now, going to close. 

I'm creating `rtm` like so: 

    var slackClient = require('slack-client');
    var WebClient = slackClient.WebClient;
    var RtmClient = slackClient.RtmClient;
    var webClient = new WebClient(bot_access_token);
    var rtm = new RtmClient(webClient, {logLevel: 'debug'});

...but the code where I'm sending the DM is in a different scope, so I don't have `bot_access_token` available, so I'm retrieving it from the `rtm` object, which is why it looks a bit convoluted.
