### ISSUE TITLE
Self user missing data in data store

### ISSUE THREAD

**Issue by aeirola** [l12s/node-slack-client#29]
When the data store initializes the cache on the RTM start message, it stores the users nicely in the cache, but then on the second to last line ([`data-store.js:L383`](https://github.com/l12s/node-slack-client/blob/342d384f890fbc127da638df8628cf479008e4b3/lib/data-store/data-store.js#L383)) overrides the current user with a plain object which is missing certain fields, such as profile data.

Would be nicer if the current user was updated with the preference data, instead of overwriting the user data. This would be accomplished by replacing the line with 

```javascript
  this.upsertUser(data.self);
```

I can make a pull-request if needed.

**Comment by l12s** [comment]
Thanks, this is totally my bad, but I forgot to close this fork when I ported the work back to https://github.com/slackhq/node-slack-client/tree/2.0.0-beta

This issue should now be fixed by a separate PR on that branch.
