### ISSUE TITLE
Handle updating models where the original model has richer properties than the newer model

### ISSUE THREAD

**Issue by l12s** [l12s/node-slack-client#5]
For example, the self property returned with rtm.start comes with a bundle of prefs that are not returned on all user calls.

**Comment by mvaragnat** [comment]
Another example just for the record, channel /rename function (channel_name message event) leaves a channel with very little properties, such as no "members" field

**Comment by l12s** [comment]
Ok, I have a first pass implementation at resolving this now in place. The data-store classes now support `upsert` methods and model classes now have an update method in place.

I believe, although I haven't done a lot of testing in actual use yet, that this should be a reasonable fix for this.
